API:
  IMAGE:
    name: api
    repository: habor.analytichpxv3.online/kubernetes-workshop/new-api
    tag: dev-da06ca5
  API_KEY: aaaaaaaaaaaa
WEB:
  IMAGE:
    name: web
    repository: habor.analytichpxv3.online/kubernetes-workshop/new-ui
    tag: dev-e6a9d14
  API_KEY: aaaaaaaaaaaa
ENV: dev
