{{ $namespace := .Release.Name }}
{{ $image := .Values.API.IMAGE.repository }}
{{ $tag := .Values.API.IMAGE.tag }}
{{ $name := .Values.API.IMAGE.name }}

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ print $namespace "-api" }}
  name: {{ print $namespace "-api" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print $namespace "-api" }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ print $namespace "-api" }}
    
    spec:
      containers:
      - image: {{ $image }}:{{ $tag }}
        name: {{ $name }}
        resources: {}
status: {}
